### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by timmo001** [timmo001/ESP8266-LED-Matrix-MQTT-Sign#1]
## Description of issue

- [x] Add missing defines to setup-template
- [x] Make date `%02d.%02d`
- [x] Add Extras
- [x] Add scrolling options from MQTT JSON payload
- [x] Reformat and cleanup code 
- [x] Test All MQTT JSON options work
- [x] Fix deps on README
- [x] Add hardware setup and examples to README
